### PR TITLE
Protect against queries EF optimizes down to dummy no-op queries when bulk updating and deleting

### LINKED ISSUE #33: Batch delete operations throw on queryables EF has optimized down to dumb no-op queries
In the following scenario:

```cs
int[] ids = Array.Empty<int>();

EFBatchOperation.For(libraryContext, libraryContext.Books).Where(book => ids.Contains(book.Id)).Delete();
```

An exception will be thrown because EF has optimized `libraryContext.Books.Where(book => ids.Contains(book.Id))` such that the SQL it produces looks something like this:

```sql
SELECT Id, Title
FROM VALUES (0, NULL)
WHERE 1 = 0
```

Which naturally has no schema or table to extract, which breaks `IQueryProvider.GetDeleteQuery` and `IQueryProvider.GetUpdateQuery`.

A solution would likely be to abort these methods if the query contains something suspicious like `WHERE 1 = 0`.

### PR DESCRIPTION
**Pull request by NetherGranite**
While this is not compatible with the refactors coming up (especially since this would need to be duplicated to the async versions of methods), this demonstrates what fixed #33 for me; I use this in production.

Bulk delete and update are changed to abort if a query appears to be a dummy query against nothing that returns nothing.

### CODE REVIEW

**Comment by RudeySH** [comment]
If your PR is ready to be merged, I don't mind merging it to master and then merge it into the refactor branch. I'm going to start building pre-release NuGet packages from that branch soon, hopefully getting it merged to master later this week.

**Comment by NetherGranite** [comment]
@RudeySH This branch is feature complete, but I also don't know if this is how you'd prefer you solve this issue. Additionally it's a pretty simple change, so it's totally up to you if this gets merged or if it's just something you throw in later 🙂

**Comment by RudeySH** [comment]
FYI, I just published 2.0.0-alpha.1, but it doesn't include this PRs changes yet. I ran into database connection issues with the alpha package, so I don't recommend using it at the moment. In the next couple of days I'll try to work on getting that fixed and merging master into the refactor branch for 2.0.0-alpha.2.

File: EntityFramework.Utilities/EntityFramework.Utilities/EFBatchOperation.cs [hunk 1]
```diff
@@ -232,6 +239,16 @@ public int Update<TP>(Expression<Func<T, TP>> prop, Expression<Func<T, TP>> modi
 			var mquery = (ObjectQuery<T>)_context.CreateObjectSet<T>().Where(updateExpression);
 			var mqueryInfo = provider.GetQueryInformation(mquery);
 
+			// If Entity Framework has optimized either query down to a query that queries against nothing and returns
+			// nothing, then abort as there is no way to somehow translate it to a delete query.
```
Comment (NetherGranite) [inline EntityFramework.Utilities/EntityFramework.Utilities/EFBatchOperation.cs:243]: @RudeySH Random thing I just noticed, if you want to fix it when you merge this into the refactors, this comment says "delete" when it should say "update," apologies.

Comment (RudeySH) [reply EntityFramework.Utilities/EntityFramework.Utilities/EFBatchOperation.cs:243]: 👍 I edited the comment in the feature/refactor branch.

**Comment by RudeySH** [comment]
[2.0.0-alpha.2](https://www.nuget.org/packages/RudeySH.EFUtilities/2.0.0-alpha.2) is out and it contains the changes from this PR, as well as a fix for the aforementioned database connection issues.
